services:
  - type: web
    name: trafficrl-api
    runtime: python
    region: oregon

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install torch==2.4.1 --index-url https://download.pytorch.org/whl/cpu

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.14"

    plan: free